// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestPatInfo.Models
{
    public partial class TestPatinfo
    {
        public int PatKey { get; set; }
        public string PatId { get; set; }
        public string PatName { get; set; }
        public string PatIdno { get; set; }
        public string PatTel { get; set; }
    }
}